# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 03c673470532d00f655f547e1d4d6ddd3f347b019b9d15c08af7b2f20365bab655b1dba92278e8d010363f9de17070cfaa5899b2f53beff4f810c8cc036c3887

test:
  secret_key_base: f3e39f3f232c1b8208e2ba910f68cf6e6236f368741478f59fa9b9646a090f671b800a3b82f1300d3eed7755af769c75f5eb02777686d00cc976ac61f0db3dfe

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
